services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./backend/notes-backend
    image: notes-backend:dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: notes
      DB_USER: notes
      DB_PASSWORD: notes
      SERVER_PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  web:
    build:
      context: ./frontend/notes-frontend
      dockerfile: Dockerfile.dev
    image: notes-frontend:dev
    environment:
      # El navegador llama a localhost:8080
      VITE_API_BASE_URL: http://localhost:8080/api/v1
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/notes-frontend:/app
      - /app/node_modules
    depends_on:
      - api
    restart: unless-stopped

volumes:
  pgdata:
